<?php

namespace Database\Seeders;

use App\Models\KpiCorporate;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KpiCorporateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kpicor = [
            [
                'corporate' => 'PT MPK',
                'goals' => 'Establish systems to maximise environmental protections',
                'kpi_corporate' => 'Minimise loss to Fire',
                'target_corporate' => 'Zero',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'Establish systems to maximise environmental protections',
                'kpi_corporate' => 'Minimise illegal logging area',
                'target_corporate' => '15% reduction from total baseline 2022',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'Implement measurement systems and strategies to protect and enrich the landscape’s  biodiversity ',
                'kpi_corporate' => 'Biodiversity periodic monitoring  ',
                'target_corporate' => 'once a year, monitoring doc completed  ',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'Implement measurement systems and strategies to protect and enrich the landscape’s  biodiversity ',
                'kpi_corporate' => 'Identification of wildlife hunting',
                'target_corporate' => 'report completed ',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'Implement strategies to improve the wellbeing of the communities around the project, reduce dependency on natural resources and reduce encroachment',
                'kpi_corporate' => 'Socialization & Implementation of Grievance policy & mechanism to society',
                'target_corporate' => 'System impelemented in 1 villages',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'Implement strategies to improve the wellbeing of the communities around the project, reduce dependency on natural resources and reduce encroachment',
                'kpi_corporate' => 'Land use planning for desa Mayak (participatory village mapping, cooperative partnership and land use mapping) ',
                'target_corporate' => 'Agreement ',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'Implement strategies to improve the wellbeing of the communities around the project, reduce dependency on natural resources and reduce encroachment',
                'kpi_corporate' => 'Monitoring and Implementation Economic empowerment project for society',
                'target_corporate' => 'Monitoring &Evaluation in 6 villages @ 1 pilot project',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'Implement strategies to improve the wellbeing of the communities around the project, reduce dependency on natural resources and reduce encroachment',
                'kpi_corporate' => 'Economic Pilot project for society',
                'target_corporate' => 'kick off 1 new pilot project in Sukamaju',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'Implement strategies to improve the wellbeing of the communities around the project, reduce dependency on natural resources and reduce encroachment',
                'kpi_corporate' => 'Improvement of community adaptation & mitigation capacity to climate change',
                'target_corporate' => 'Monitor Implementation of Village regulation  (Perdes) in 2 villages',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'Implement strategies to improve the wellbeing of the communities around the project, reduce dependency on natural resources and reduce encroachment',
                'kpi_corporate' => 'Improvement of community adaptation & mitigation capacity to climate change',
                'target_corporate' => 'New Village regulation (Perdes) in 2 other villages',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'Implement robust culture of safety and wellbeing for staff and stakeholders',
                'kpi_corporate' => 'Maximise Personal Safety',
                'target_corporate' => 'Satisfactory',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'Establish a sustainable Nature Based Solutions model of funding to protect the peat forest ecosystem.',
                'kpi_corporate' => 'RKU Approved',
                'target_corporate' => 'Completed',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'Establish a sustainable Nature Based Solutions model of funding to protect the peat forest ecosystem.',
                'kpi_corporate' => 'PDD Validation ',
                'target_corporate' => 'Completed',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'Establish a sustainable Nature Based Solutions model of funding to protect the peat forest ecosystem.',
                'kpi_corporate' => 'MR verification',
                'target_corporate' => 'Completed',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'Implement robust administrative and budget compliance',
                'kpi_corporate' => 'Budget compliance',
                'target_corporate' => 'Zero over budget',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'Implement robust administrative and budget compliance',
                'kpi_corporate' => 'Budget compliance',
                'target_corporate' => 'Efficiency min 5%',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'Implement robust administrative and budget compliance',
                'kpi_corporate' => 'No penalty or red notice from government',
                'target_corporate' => 'Zero',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
            [
                'corporate' => 'PT MPK',
                'goals' => 'No Goals',
                'kpi_corporate' => 'Non KPI',
                'target_corporate' => 'Non Target',
                'year' => '2023',
                'bobot' => '0',
                'user_id' => '1',
                'updated' => '1',
                'created_at' => date(now()),
                'updated_at' => date(now()),
            ],
        ];
        KpiCorporate::insert($kpicor);
    }
}